# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Key mappings for bépo
bindkey -M viins "^@" vi-cmd-mode
bindkey -M viins "$key_info[Control]R" \
    history-incremental-pattern-search-backward
bindkey -M vicmd é vi-forward-word
bindkey -M vicmd É vi-forward-blank-word
bindkey -M vicmd c vi-backward-char
bindkey -M vicmd C vi-beginning-of-line
bindkey -M vicmd r vi-forward-char
bindkey -M vicmd R vi-end-of-line
bindkey -M vicmd t down-line-or-history
bindkey -M vicmd s up-line-or-history
bindkey -M vicmd T vi-join
bindkey -M vicmd h vi-find-next-char-skip
bindkey -M vicmd H vi-find-prev-char-skip
bindkey -M vicmd f vi-find-next-char
bindkey -M vicmd F vi-find-prev-char
bindkey -M vicmd l vi-change
bindkey -M vicmd L vi-change-eol
bindkey -M vicmd j vi-replace-chars
bindkey -M vicmd J vi-replace
bindkey -M vicmd k vi-substitute
bindkey -M vicmd K vi-change-whole-line
bindkey -M vicmd « vi-unindent
bindkey -M vicmd » vi-indent
bindkey -M vicmd , vi-repeat-find
bindkey -M vicmd ';' vi-rev-repeat-find
bindkey -M vicmd Y vi-yank-eol
bindkey -M vicmd U redo
bindkey -M vicmd S run-help

#todo.sh
alias t=todo.sh
export TODOTXT_DEFAULT_ACTION=ls

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
